language : node_js

node_js: stable

install:
- yarn

stages:
 - name: deploy

jobs:
 include:

   - stage: deploy
     script:
       - yarn build-bundle

     deploy:
       provider: npm
       email: javpeiwen2010@gmail.com
       api_key: "$npm_token"
       skip_cleanup: true
       on:
         branch: master