language : node_js

node_js: stable

install:
- yarn

stages:
 - name: deploy

jobs:
 include:

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - yarn build-bundle
       - echo "NPM Building Finished."
       - echo "NPM Publish Started ..."
       - cd lib
       - npm publish
       - echo "NPM Publish Finished."

     deploy:
       provider: npm
       email: javpeiwen2010@gmail.com
       api_key: "$npm_token"
       skip_cleanup: true
       on:
         all_branches: true