language : node_js

node_js: stable

install:
- yarn

stages:
 - name: deploy
   if: branch = master

jobs:
 include:

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - yarn build-bundle
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: javpeiwen2010@gmail.com
       api_key: "$npm_token"
       skip_cleanup: true
       on:
         branch: master